name: Ahoy Dev-Build for ESP8266/ESP32

on:
  push:
    branches: development*
    paths-ignore:
    - '**.md' # Do no build on *.md changes
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: development03
    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 7

    - name: Cache Pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.x"

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Convert HTML files
      working-directory: src/web/html
      run: python convert.py

    - name: Run PlatformIO
      run: pio run -d src --environment esp8266-release --environment esp8285-release --environment esp8266-nokia5110 --environment esp8266-ssd1306 --environment esp32-wroom32-release --environment esp32-wroom32-nokia5110 --environment esp32-wroom32-ssd1306

    - name: Rename Binary files
      id: rename-binary-files
      working-directory: src
      run: python ../scripts/getVersion.py >> $GITHUB_OUTPUT

    - name: Set Version
      uses: cschleiden/replace-tokens@v1
      with:
        files: tools/esp8266/User_Manual.md
      env:
          VERSION: ${{ steps.rename-binary-files.outputs.name }}

    - name: Create Manifest
      working-directory: src
      run: python ../scripts/buildManifest.py

    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ahoydtu_dev
        path: |
          src/firmware/*
          src/User_Manual.md
          src/install.html

